### ISSUE TITLE
Tutorial set-up needs corrections 

### ISSUE THREAD

**Issue by pjgoodall** [JuliaAcademy/DataFrames#11]
the notebook [Environment setup.ipynb](https://github.com/JuliaAcademy/DataFrames/blob/f2aabbf539ed16dbafdaa718514d1d9e9383b926/1.%20Environment%20setup.ipynb) has some important errors - that should be simple to correct by someone with masterful experience in conda/julia

* The python setup depends on whatever python is running on the student's workstation, which does result in frustrating errors for beginners.
* The `matplotlib` python library is not installed on my base system, so the notebook fails. Other students have experienced other similar problems

Fully reproducible environments are the key.

I believe Julia uses `conda` internally to build python environments. See how `IJulia` loads - it uses `conda` to establish a Jupyter notebook environment. I've only been trying Julia for a few days, so I haven't enough experience to help yet. I have seen a fully worked example that started with disconnecting from the local python environment using ` ENV["PYTHON"]=""`, and then using conda within julia, to build a python environment. I can't find that example again.

See:

* [Conda.jl](https://github.com/JuliaPy/Conda.jl)
* [PyCall README](https://github.com/JuliaPy/PyCall.jl/blob/8a98fb45ef39d09e11c1270e9120a32df2578d50/README.md)
* [FluxML / model-zoo](https://github.com/FluxML/model-zoo) uses [gitpod.io](https://www.gitpod.io/) for some examples. gitpod could to be encouraged to support julia better.

**Comment by bkamins** [comment]
Indeed - I think that in the future we should switch from PyPlot.jl to some other plotting backend. For the time being do you think it will be enough to add a link to https://github.com/JuliaPy/PyPlot.jl#installation where the instructions how to set up PyPlot properly are provided?

**Comment by bkamins** [comment]
I have added some more instructions to the notebooks. Can you please have a look if they look clear for you.

**Comment by pjgoodall** [comment]
@bkamins 
Thanks very much for your attention to this! I've been slow getting back to you, because I've been learning to configure too many things...

`isfile.(["Project.toml", "Manifest.toml"])` behaved correctly.

the `] status`  and `] instantiate` cells do not print any output,  but if I activate the project from a repl I get:
```
 pkg> activate .
  Activating environment at `~/Tutorials/Julia-Tutorials/JuliaAcademy/DataFrames/Project.toml`

(DataFrames) pkg> st
      Status `~/Tutorials/Julia-Tutorials/JuliaAcademy/DataFrames/Project.toml`
  [69666777] Arrow v1.6.0
  [336ed68f] CSV v0.8.5
  [a93c6f00] DataFrames v1.2.0
  [da1fdf0e] FreqTables v0.4.4
  [38e38edf] GLM v1.5.1
  [b98c9c47] Pipe v1.3.0
  [d330b81b] PyPlot v2.9.0
  [1986cc42] Unitful v1.9.0
```
Which looks like the correct result, and was quite clear to me.

I tried the notebook again with the python `matplotlib` python package uninstalled from my enclosing conda environment, and it all instantiated correctly . But the first exercise could not find it.

**Comment by pjgoodall** [comment]
I think I have a simple solution which gets julia to install everything including `Jupyter notebook` and `MatPlotLib` automatically using its internal `conda` environment. 

The user should just have to start the julia repl, activate the tutorial environment, and run `notebook()`.

You may know how to set the julia project `.toml` to do most of this.

in the repl:

```
>
ENV["PYTHON"]=""
using Pkg
Pkg.activate()
Pkg.add("PyCall")
Pkg.build("PyCall")
Pkg.add("IJulia")
using IJulia
notebook(;dir=pwd(), detached=true)
```


## References

1. [The PyPlot module for Julia ](https://github.com/JuliaPy/PyPlot.jl#the-pyplot-module-for-julia)
2. [Public API - IJulia](https://julialang.github.io/IJulia.jl/dev/library/public/)

**Comment by pjgoodall** [comment]
I'm using this now - works for me without any environment other than julia - no need to install `Jupyter notebook`, `MatPlotLib` etc...

`Project.toml `looks like this
``` toml
[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
```

Use this command line in the Tutorial directory:

```
PYTHON="" julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate(); using IJulia; notebook(;dir=pwd(), detached=true) ' 
```

`PYTHON="" julia...` sets the python environment to empty before running julia.

I hope that is of some use...
